site_name: Documentation BTS SIO
site_description: Documentation technique pour le BTS SIO
site_author: Lilian
site_url: https://seigi06.github.io/Portfolio-LP/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - navigation.top
    - navigation.footer
    - navigation.tracking
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Accueil: index.md
  - À propos: about/index.md
  - Easter Egg: easter-egg/index.md
  - Administration Système:
    - Commandes Multi-OS: commandes-multi-os/index.md
    - Linux: linux/index.md
    - Active Directory: active-directory/index.md
    - Proxmox: Proxmox/index.md
    - GLPI: glpi/index.md
  - Réseaux:
    - pfSense: pfsense/index.md
    - Nmap: nmap/index.md
  - Serveurs Web: serveurs-web/index.md

extra_css:
  - hide_nav.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - footnotes
  - toc:
      permalink: true
