name: Déploiement du site

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Vérifier les fichiers
        run: |
          echo "Contenu du répertoire :"
          ls -la
          echo "Fichiers HTML présents :"
          find . -name "*.html"

      - name: Déployer sur GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Le dossier à déployer (racine du projet)
          branch: gh-pages # La branche de déploiement
          clean: true # Nettoyer les fichiers existants avant le déploiement
          commit-message: "Déploiement automatique du site" # Message de commit personnalisé 